// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe13aZAje1uh3xXRaVz3CdP-qWVzmEYg4',
    appId: '1:1010282388286:web:946195519e625a1d8eea6f',
    messagingSenderId: '1010282388286',
    projectId: 'vircloset',
    authDomain: 'vircloset.firebaseapp.com',
    storageBucket: 'vircloset.appspot.com',
    measurementId: 'G-T3WCL22X2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK3ICx6AxkuGa6wvsc4mDZv-_PEXYRHoc',
    appId: '1:1010282388286:android:cd06f12034b93d678eea6f',
    messagingSenderId: '1010282388286',
    projectId: 'vircloset',
    storageBucket: 'vircloset.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdrF9zuOKxgKtBhQVIiCJ6P9S-293Vod4',
    appId: '1:1010282388286:ios:07341a681015585b8eea6f',
    messagingSenderId: '1010282388286',
    projectId: 'vircloset',
    storageBucket: 'vircloset.appspot.com',
    iosBundleId: 'clave.armario.vircloset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdrF9zuOKxgKtBhQVIiCJ6P9S-293Vod4',
    appId: '1:1010282388286:ios:07341a681015585b8eea6f',
    messagingSenderId: '1010282388286',
    projectId: 'vircloset',
    storageBucket: 'vircloset.appspot.com',
    iosBundleId: 'clave.armario.vircloset',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe13aZAje1uh3xXRaVz3CdP-qWVzmEYg4',
    appId: '1:1010282388286:web:e6f1c171e4916f618eea6f',
    messagingSenderId: '1010282388286',
    projectId: 'vircloset',
    authDomain: 'vircloset.firebaseapp.com',
    storageBucket: 'vircloset.appspot.com',
    measurementId: 'G-VQGWBYR963',
  );
}
